### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by funzik** [ESX-Org/esx_phone#17]
the phone don't work in game... i don't know why because i don't have error in console...

**Comment by RomainLanz** [comment]
Hey @funzik ! 👋 

I got no problem with the phone on my system.
It's probably an issue on your side, you should try to reinstall it and other dependencies who use it.

**Comment by funzik** [comment]
sorry i have help in your discord, esx phone workn it's because i have a bad order of start ressources in server.cfg
