### ISSUE TITLE
Phone don't send message out to Police,EMS,Mechanic or Taxi.

### ISSUE THREAD

**Issue by Delux2** [ESX-Org/esx_phone#19]
Phone works,it comes up in the game and I can write a message.Then on the left side there comes a message saying "Message has sent out" or something and then nothing happens.I can't see the message and I'm police officer and on duty but I can't see the "Phone message".Need help please!

**Comment by dunof** [comment]
Same problem here!

**Comment by dunof** [comment]
I solved my problem by starting esx_phone before the jobs on server.cfg
