### ISSUE TITLE
Pressing A on an xbox controller causes phone to appear

### ISSUE THREAD

**Issue by Adam-Ant** [ESX-Org/esx_phone#22]
When A is pressed, the phone menu pops up, making  it impossible to run.

Tested on Windows 10, latest version of Fivem, es and esx.

**Comment by ElPumpo** [comment]
This can very easily be fixed, I'll propose a PR fixing this. It is really annoying I know...

**Comment by ElPumpo** [comment]
Fixed in 45a3f8e3d24da1580fcf2b65054d5d04f728d920

**Comment by vpayso** [comment]
how you fixed it?
