### ISSUE TITLE
Cannot delete contacts

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_phone#24]

**Comment by pleasega** [comment]
got this issue done but havent done the localization, do i create a pr first?

**Comment by ElPumpo** [comment]
Awesome, you can do propose an PR and let me do the rest if you're lazy.

**Comment by pleasega** [comment]
done #25

**Comment by ElPumpo** [comment]
Fixed in 7b72befd78eb3fabf020c5c007496ab202cad602
