### ISSUE TITLE
 Can not contact a police, ambulance or mechanic

### ISSUE THREAD

**Issue by Korgron** [ESX-Org/esx_phone#27]
The problem is that i can not call a police, ambulance or mechanic. I send a message, but the job receives no notification. I'm not sure if it's issues on the phone or the policejob. So please help me or check the issue and fix it.

**Comment by Korgron** [comment]
Oh, I have fixed the problem myself: D still thanks for reading ^^

**Comment by FiveMPlayer** [comment]
How did you fix it ?

**Comment by Korgron** [comment]
The fix of my problem was, that i have start esx_phone before i start all my Jobs
Example:
(server.cfg)
start esx_phone

start esx_policejob
start esx_ambulancejob
start esx_mecanojob

Sry if my english is bad xD
