### ISSUE TITLE
Bug with call police or ambulance

### ISSUE THREAD

**Issue by molasmolas212** [ESX-Org/esx_phone#30]
hello github, recently I walk with an error, I call the ambulance or the police and they do not receive the calls on the mobile phone I have the dependencies esx_phone, esx_ambulance, esx_police Prints: http://prntscr.com/jwf8z1 http: // prntscr .com / jwf9e9

**Comment by Coff3** [comment]
The server hasn't loaded your character yet you see that because you have no phone number so the server dosen't know that you are a player.

**Comment by ElPumpo** [comment]
It's because you started the jobs before esx_phone. They must be loaded **after** esx_phone
