### ISSUE TITLE
Esx Phone error

### ISSUE THREAD

**Issue by Malviaa** [ESX-Org/esx_phone#44]
Hi! I got some problems with esx_phone. When a new player join the server I get error code in the cmd. I have no idea whats causing this problem... I have the start order
start es_extended
start esx_phone
 All other esx is working fine.
![preview](https://cdn.discordapp.com/attachments/486612402721390602/506577257129705482/error.png)

**Comment by ElPumpo** [comment]
We dont know either install it properly
