### ISSUE TITLE
Police are not receiving messages.

### ISSUE THREAD

**Issue by Tanner-S** [ESX-Org/esx_phone#46]
When I try to send a message to the police job through the phone, the police don't receive it. I've looked at related issues and yes, I'm starting esx_phone before any of the jobs in the server.cfg. It is saying 'Your message has been sent' when the client sends it as well as it pops up in console saying the message is sent ('esx_phone: MESSAGE => TannerS@police: Testing') but no notification nor is there anything in message history, I checked other jobs and it works perfectly fine. I can't figure out what's going on for the life of me.

**Comment by Oskar461** [comment]
Did you solve it?
