### ISSUE TITLE
Phone translation error when_policejob

### ISSUE THREAD

**Issue by Briixain** [ESX-Org/esx_phone#50]
I recently duplicated esx_policejobs to make esx_bcso.  I've updated in server/client main.lua all instances to show for 'sheriff' et al. When I use the esx_phone in-game (screenshots provided) it has 2 problems:  1) translation not found  (my original file esx_policejob is configured (en) so the duplicate was as well. and 2) When I press "E" to respond to the call nothing happens.  My server is built from Zap and the esx_phone is above all the jobs in the server.cfg.  Ideally, I would like the script to use just the police app on the phone and alert both departments.  

![20190427065846_1](https://user-images.githubusercontent.com/50054436/56852594-05214c80-68d2-11e9-9cdd-2b7ac105c75a.jpg)
![20190427065752_1](https://user-images.githubusercontent.com/50054436/56852595-0783a680-68d2-11e9-9427-3986b8bf1d7d.jpg)

Thanks!

**Comment by ji-a-kang** [comment]
Did you add ['PHONE_SHERIFF'] in locale/en.lua?? Can you show me 'en.lua'?
